services:
  drupal:
    image: drupal:10-apache   #drupal:11-apache
    container_name: drupal
    restart: unless-stopped
    environment:
      - PATH=/greeneye-tools:$PATH    
    volumes:
      - cms_modules:/var/www/html/modules
      - cms_profiles:/var/www/html/profiles
      - cms_themes:/var/www/html/themes
      - cms_sites:/var/www/html/sites
      - tools:/greeneye-tools
    depends_on:
      - db
    networks:
      - frontend
      - backend

  db:
    image: postgres:17.5-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: drupaldb
      POSTGRES_USER: drupaluser
      POSTGRES_PASSWORD: drupalpassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - frontend
      - backend

volumes:
  cms_modules:
  cms_profiles:
  cms_themes:
  cms_sites:
  tools:
  pg_data:

networks:
  frontend:
  backend:
